name: masonry_test
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  masonry:
    path: ../masonry

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^2.4.0
